# Generated by Django 4.2.27 on 2025-12-03 11:44

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('service', models.CharField(choices=[('gestion-rh', 'Gestion RH externalisée'), ('paie', 'Paie externalisée'), ('recrutement', 'Recrutement & intégration'), ('creation-entreprise', 'Création / structuration d’entreprise'), ('multi', 'Plusieurs services'), ('autre', 'Autre / à préciser')], default='gestion-rh', max_length=40, verbose_name='Service souhaité')),
                ('message', models.TextField(verbose_name='Message')),
                ('consent', models.BooleanField(default=True, verbose_name='J’accepte d’être recontacté')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(default='Abidjan, Côte d’Ivoire', max_length=150, verbose_name='Localisation')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('short_description', models.TextField(verbose_name='Résumé de l’offre')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée sur le site')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de candidature')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre interne')),
                ('subject', models.CharField(max_length=255, verbose_name="Objet de l'email")),
                ('body_html', models.TextField(help_text='Contenu de la newsletter (HTML).', verbose_name='Contenu HTML')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date/heure d'envoi prévue")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sent', 'Envoyée')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Campagne newsletter',
                'verbose_name_plural': 'Campagnes newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif / abonné')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom du pack')),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('price_label', models.CharField(help_text="Ex: 'À partir de 250 000 FCFA / mois' ou 'Sur devis'", max_length=150, verbose_name='Libellé de prix')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Pour tri / stats, optionnel', max_digits=12, null=True, verbose_name='Montant numérique (optionnel)')),
                ('target_segment', models.CharField(blank=True, help_text='Ex: TPE, PME, Grandes entreprises', max_length=150, verbose_name='Segment cible')),
                ('features', models.TextField(help_text='Saisir une fonctionnalité par ligne', verbose_name='Points forts (1 par ligne)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pack tarifaire',
                'verbose_name_plural': 'Packs tarifaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(blank=True, help_text="Ex: 'fas fa-file-invoice-dollar'", max_length=80, verbose_name='Icône Font Awesome')),
                ('short_description', models.TextField(verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('initials', models.CharField(help_text="Ex: 'AK', 'SD'", max_length=4, verbose_name='Initiales')),
                ('role', models.CharField(max_length=150, verbose_name='Poste')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('quote', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Note (1-5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('cv', models.FileField(upload_to=website.models.cv_upload_path, verbose_name='CV')),
                ('cover_letter', models.FileField(upload_to=website.models.cover_letter_upload_path, verbose_name='Lettre de motivation')),
                ('notes', models.TextField(blank=True, verbose_name='Message / Notes du candidat')),
                ('processed', models.BooleanField(default=False, verbose_name='Dossier traité')),
                ('status', models.CharField(default='reçu', help_text='Ex: reçu, en cours, retenu, rejeté...', max_length=30, verbose_name='Statut')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.joboffer', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
